---
- name: "Get CPU Temperature"
  hosts: all
  user: ansible
  become: yes
  tasks:
    - name: "Get CPU Temperature"
      command: vcgencmd measure_temp
      # shell: vcgencmd measure_temp
      register: output
    - debug: msg="{{ output.stdout }}"
...

