---
- name: "Shutdown all Raspberry Pi's"
  hosts: all
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: "Poweroff"
      command: shutdown -P
      # shell: shutdown -P
...
