---
# - hosts: master
- name: "Setting up Ansible User"
  hosts: all
  user: pi
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: "Add the ansible user"
      user:
        name: ansible
        comment: "Ansible User"
        createhome: yes
    - name: "Add the user to sudoer"
      copy:
        content: "ansible ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/ansible
        force: yes
        mode: 0440
    - name: "Set authorized key"
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/tux/.ssh/id_rsa.pub') }}"
...
