---
- name: "ansible-vault test playbook example"
  hosts: "all"
  connection: "local"
  vars:
    username: "tux"
  vars_files:
    - "password.yml"
  tasks:
    - name: "Get the current date and time"
      command: "date"
      register: "todays_date"
      check_mode: "no"

    - name: "Print current Date"
      debug:
        msg: "Date/Time: {{ todays_date.stdout }}"

    - name: "Print Username and Password"
      debug:
        msg: "Username: {{ username }}, Password: {{ password }}"
